on:
  push:
    branches:
      - production

jobs:
  docker-start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This step is necessary to ensure the repo is checked out

    - name: Create PEM Key
      run: |
        mkdir -p ~/.ssh
        echo $SSH_KEY > ~/.ssh/alan.pem
        chmod 600 ~/.ssh/alan.pem
        openssl rsa -in ~/.ssh/alan.pem -check
        ssh-keyscan ec2-18-236-74-56.us-west-2.compute.amazonaws.com > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        echo "Private Key Content (first 5 lines):"
        echo "$SSH_KEY" | head -n 5
        
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Connect to EC2 and execute commands
      run: |
        ssh -vvv -i ~/.ssh/alan.pem ec2-user@ec2-18-236-74-56.us-west-2.compute.amazonaws.com /bin/bash <<'EOF'
        echo "Successfully connected to EC2!"
        # GO TO DIRECTORY CONTAINING GIT REPOSITORY
        cd /home/ec2-user/tst_dir/dockerized-scheduler
        # SHUT DOWN CONTAINERS
        sudo docker-compose down
        # GET LATEST REPOSITORY
        git pull
        # BUILD NEW CONTAINERS
        sudo docker-compose up --build
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
