name: Docker Container Build and Test

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        version: '23.0.1'  # Specify the Docker version you want to use

    - name: Build and Test Container 1
      run: |
        docker build -t api:v1 ./API 
        docker run -d --name restapi api:v1
        docker ps  # Verify the container is running
        docker logs my-container-1  # Check the container logs for any errors
        # Optionally test the container (e.g., if it's a web app)
        docker exec my-container-1 curl -f http://localhost:80  # Adjust the port if needed
        docker stop my-container-1  # Stop the container after test
        docker rm my-container-1  # Remove the container

    - name: Build and Test Container 2
      run: |
        docker build -t my-container-2 ./Backend
        docker run -d --name my-container-2 my-container-2
        docker ps  # Verify the container is running
        docker logs my-container-2  # Check the container logs for any errors
        # Optionally test the container (e.g., if it's a web app)
        docker exec my-container-2 curl -f http://localhost:80  # Adjust the port if needed
        docker stop my-container-2  # Stop the container after test
        docker rm my-container-2  # Remove the container

    - name: Build and Test Container 3 (if applicable)
      run: |
        docker build -t my-container-3 ./Web
        docker run -d --name my-container-3 my-container-3
        docker ps  # Verify the container is running
        docker logs my-container-3  # Check the container logs for any errors
        # Optionally test the container (e.g., if it's a web app)
        docker exec my-container-3 curl -f http://localhost:80  # Adjust the port if needed
        docker stop my-container-3  # Stop the container after test
        docker rm my-container-3  # Remove the container
